import base64, html, mimetypes
from pathlib import Path
ROOT=Path(__file__).resolve().parents[1]
def _data_uri(rel):
 p=ROOT/rel
 if not p.exists(): return None
 mime=mimetypes.guess_type(p.name)[0] or 'image/jpeg'
 return f"data:{mime};base64,"+base64.b64encode(p.read_bytes()).decode()
def inject_css():
 import streamlit as st
 st.markdown(r'''<style>
:root{--red:#E54456;--ink:#1B1B1B;--line:#E9E9E9;--beige:#F7F1E5;--blue:#EEF4FF}
*{font-family:Pretendard,"Noto Sans KR",Arial,sans-serif}.stApp{background:#fff;color:var(--ink)}
/* match user's 1338px reference: ~59px margins / ~1220px content */
.block-container{width:calc(100% - 112px)!important;max-width:1220px!important;padding:1.2rem 0 4rem!important;margin:0 auto!important}
header[data-testid="stHeader"],[data-testid="stSidebar"],[data-testid="stSidebarCollapsedControl"]{display:none!important}
.stButton>button{border-radius:999px;border:1px solid #E4E4E4;background:#fff;color:#252525;font-weight:650;min-height:38px}.stButton>button:hover{border-color:#CACACA;color:var(--red)}.stButton>button[kind="primary"]{background:var(--ink);color:#fff;border-color:var(--ink)}
/* exact BI asset */
.brand-bi{display:block;width:242px;height:auto;margin:0;padding:0}.brand-bi-link{display:inline-block;line-height:0;text-decoration:none}
.st-key-topnav{padding-top:0}.st-key-topnav .stButton>button{border:none!important;background:transparent!important;box-shadow:none!important;border-radius:0!important;min-height:34px!important;padding:.15rem .08rem!important;font-size:12px!important;font-weight:600!important}.st-key-topnav .stButton>button:hover{color:#111!important}.nav-icon{text-align:center;font-size:15px;font-weight:700;padding-top:7px}.nav-icon.bag{font-size:10px;letter-spacing:.05em;padding-top:10px}.nav-rule{height:1px;background:#EDEDED;margin:.72rem 0 1.75rem}
/* exact main 2 layout */
.st-key-hero_row [data-testid="stHorizontalBlock"]{gap:40px!important;align-items:flex-start!important}.st-key-discovery_panel{background:#fff;padding:0!important}.discovery-visual{width:100%;aspect-ratio:1.3077/1;background:#E5E2DC;background-size:cover;background-position:center}.asset-fallback{height:100%;display:flex;align-items:center;justify-content:center;color:#8D8D8D;font-size:11px;font-weight:850;letter-spacing:.13em}.discovery-copy{padding:1.05rem 1.55rem .32rem}.eyebrow{font-size:11px;font-weight:850;letter-spacing:.08em;color:#555;margin-bottom:.6rem}.eyebrow.red{color:var(--red)}.banner-title{font-size:30px;line-height:1.12;font-weight:900;letter-spacing:-.048em;margin:.12rem 0 .62rem}.banner-sub{color:#7A7A7A;font-size:11px}.discovery-cta{height:47px;margin:.58rem 1.48rem 0;border-radius:999px;background:#1B1B1B;color:#fff;display:flex;align-items:center;justify-content:center;font-size:12px;font-weight:800}.discovery-cta span{color:#E7E21B;font-size:16px;margin:0 4px}.st-key-discovery_panel .st-key-banner_cta_hit{height:1px!important;overflow:hidden!important;margin:0!important;padding:0!important;opacity:0!important}.st-key-discovery_panel .st-key-banner_cta_hit button{height:1px!important;min-height:1px!important}.st-key-discovery_panel [data-testid="stHorizontalBlock"]{margin-top:.28rem}.st-key-discovery_panel [data-testid="stHorizontalBlock"] .stButton>button{width:32px!important;min-height:32px!important;height:32px!important;padding:0!important;font-size:13px!important}
.st-key-finder_console{border:1px solid #EAEAEA;border-radius:28px;padding:1.58rem 1.72rem 1.15rem;background:#fff;box-shadow:0 8px 30px rgba(0,0,0,.014)}.hero-title{font-size:42px;line-height:1.06;letter-spacing:-.058em;margin:.05rem 0 1.24rem;font-weight:900}div[data-baseweb="input"]>div{min-height:43px!important;border-radius:5px!important;background:#F1F2F5!important;border-color:#F1F2F5!important}.st-key-finder_console .stButton>button[kind="primary"]{min-height:43px!important;height:43px!important;font-size:12px!important}.helper-label{font-size:10px;color:#777;margin:1.15rem 0 .42rem;font-weight:750}.st-key-finder_console .stButton>button:not([kind="primary"]){border:none!important;background:#F4F4F5!important;color:#373737!important;border-radius:4px!important;min-height:30px!important;padding:.20rem .42rem!important;font-size:10px!important;font-weight:600!important;white-space:nowrap!important;overflow:hidden!important;text-overflow:ellipsis!important}
.live-board{margin-top:1rem;background:var(--beige);border-radius:18px;padding:.92rem 1.12rem .95rem}.live-head{display:flex;justify-content:space-between;align-items:center;font-size:9px;font-weight:850}.live-dot{display:inline-block;width:8px;height:8px;border-radius:50%;background:#28A36A;margin-right:7px}.live-time{font-size:12px;font-weight:850}.live-body{display:grid;grid-template-columns:1.25fr 1.8fr .82fr;gap:10px;align-items:end;margin-top:.55rem}.live-kicker{font-size:12px;font-weight:800;letter-spacing:-.025em}.live-main{display:flex;align-items:baseline;justify-content:center;gap:5px}.live-prefix{font-size:10px;color:#777;font-weight:700}.live-number{font-size:39px;line-height:1;font-weight:900;color:#941D2A;letter-spacing:-.055em}.live-unit{font-size:11px;font-weight:850}.live-brand{font-size:11px;font-weight:850;text-align:right}
.quick-title{font-size:25px;line-height:1.08;font-weight:900;letter-spacing:-.047em;margin:1.42rem 0 .78rem .1rem}.circle-image{width:94px;height:94px;max-width:100%;margin:0 auto .18rem;border-radius:50%;background:#E4E1DC;background-size:cover;background-position:center;overflow:hidden}.circle-placeholder{font-size:8px}.st-key-hero_row [class*="st-key-quick_item_"] .stButton>button{border:none!important;background:transparent!important;border-radius:0!important;box-shadow:none!important;min-height:26px!important;height:26px!important;padding:0!important;font-size:11px!important;font-weight:700!important;white-space:nowrap!important;overflow:hidden!important;text-overflow:ellipsis!important}.st-key-hero_row [class*="st-key-quick_item_"] .stButton>button:hover{color:#111!important}
.section-gap{height:2.5rem}.section-title-row{margin:1.7rem 0 1rem}.section-title-main{font-size:25px;font-weight:900;letter-spacing:-.04em}.section-title-sub{color:#888;font-size:12px;margin-top:.15rem}.page-title{font-size:38px;line-height:1.15;letter-spacing:-.04em;margin:.1rem 0 1.3rem}
.product-card{border:1px solid #ECECEC;border-radius:18px;overflow:hidden;background:#fff;margin-bottom:.35rem}.product-image{height:245px;background:linear-gradient(135deg,#EFECE7,#DDE1E4);background-size:cover;background-position:center;display:flex;align-items:center;justify-content:center}.product-image span{color:#989898;font-size:10px;font-weight:850;letter-spacing:.09em}.product-copy{padding:.9rem 1rem 1rem}.product-brand{font-size:10px;color:#888;font-weight:750;margin-bottom:.2rem}.product-name{font-size:14px;line-height:1.35;font-weight:850;min-height:38px}.product-price{font-size:16px;font-weight:900;margin-top:.4rem}.product-meta{font-size:10px;color:#8A8A8A;margin-top:.35rem}.badge{display:inline-block;font-size:9px;font-weight:850;color:#fff;background:var(--red);padding:3px 7px;border-radius:999px;margin-bottom:.42rem}[class*="st-key-product_"] .stButton>button{border:none!important;background:transparent!important;border-radius:0!important;min-height:26px!important;padding:.05rem .1rem!important;font-size:11px!important;color:#555!important;justify-content:flex-start!important}
.search-summary{background:#FAFAFA;border-radius:18px;padding:1rem 1.15rem;margin:1rem 0 1.4rem}.result-title{font-size:17px;font-weight:750}.chip-row{margin-top:.7rem;display:flex;flex-wrap:wrap;gap:7px}.filter-chip{background:#FFF0F2;border:1px solid #F2B6BF;color:#C92D45;font-size:11px;font-weight:850;padding:6px 10px;border-radius:999px}.filter-title{font-size:16px;font-weight:850;margin-bottom:.9rem}.filter-count{background:var(--beige);padding:.8rem 1rem;border-radius:14px;margin-top:1rem;font-size:13px}.empty-box{border:1px dashed #D9D9D9;border-radius:20px;padding:3rem;text-align:center}.empty-title{font-size:17px;font-weight:850}.muted{color:#888;font-size:12px;margin-top:.35rem}.brand-index{line-height:2.1;color:#555;border-top:1px solid #EEE;border-bottom:1px solid #EEE;padding:1rem 0;margin-bottom:1.5rem}.brand-card{border:1px solid #ECECEC;border-radius:18px;padding:1.2rem;min-height:125px;margin-bottom:.5rem}.brand-card-name{font-size:18px;font-weight:850}.brand-card-desc,.brand-desc{color:#777;font-size:12px;margin-top:.45rem;line-height:1.55}.product-image-tall{height:610px;border-radius:24px;background:linear-gradient(135deg,#EFECE7,#D9DDE1);background-size:cover;background-position:center;display:flex;align-items:center;justify-content:center}.detail-title{font-size:34px;line-height:1.2;letter-spacing:-.04em;margin:.35rem 0 .7rem}.detail-price{font-size:24px;font-weight:900;margin-bottom:1.25rem}.match-label{color:var(--red);font-size:11px;font-weight:900;letter-spacing:.08em;margin-top:1.5rem}.why-box{background:var(--blue);border-radius:18px;padding:1rem 1.1rem;margin:1.1rem 0 1rem}.why-title{color:#3565BC;font-size:12px;font-weight:900;margin-bottom:.35rem}.why-copy{font-size:13px;line-height:1.6;color:#3E4652}
.floating-tools-image{position:fixed;right:0;top:480px;width:80px;height:auto;z-index:50;pointer-events:none}
@media(max-width:900px){.block-container{width:calc(100% - 28px)!important;max-width:none!important;padding-top:.7rem!important}.st-key-topnav [data-testid="column"]:not(:first-child){display:none}.brand-bi{width:220px}.st-key-hero_row [data-testid="stHorizontalBlock"]{display:flex!important;flex-direction:column-reverse!important;gap:1rem!important}.st-key-hero_row [data-testid="column"]{width:100%!important;flex:1 1 100%!important}.hero-title{font-size:38px}.st-key-finder_console{padding:1.15rem 1rem 1rem;border-radius:22px}.live-body{grid-template-columns:1fr;gap:6px}.live-main{justify-content:flex-start}.live-brand{text-align:left}.live-number{font-size:36px}.discovery-visual{aspect-ratio:1.2/1}.banner-title{font-size:26px}.quick-title{font-size:23px}.circle-image{width:72px;height:72px}.floating-tools-image{display:none}.product-image{height:190px}.product-image-tall{height:430px}}
</style>''',unsafe_allow_html=True)
def asset_image_html(rel,fallback_label='IMAGE',class_name='discovery-visual'):
 uri=_data_uri(rel)
 return f"<div class='{class_name}' style=\"background-image:url('{uri}')\"></div>" if uri else f"<div class='{class_name}'><div class='asset-fallback'>{html.escape(fallback_label)}</div></div>"
def circle_image_html(rel,label=''):
 uri=_data_uri(rel)
 return f"<div class='circle-image' style=\"background-image:url('{uri}')\"></div>" if uri else f"<div class='circle-image'><span class='circle-placeholder'>{html.escape(label[:7])}</span></div>"
def section_title(title,subtitle=''):
 import streamlit as st
 st.markdown(f"<div class='section-title-row'><div class='section-title-main'>{html.escape(str(title))}</div><div class='section-title-sub'>{html.escape(str(subtitle))}</div></div>",unsafe_allow_html=True)
def product_card_html(row):
 badge=str(row.get('badge','') or ''); bh=f"<div class='badge'>{html.escape(badge)}</div>" if badge else ''
 maxs=float(row.get('max_size',0)); sl=f'{int(maxs)}까지' if maxs>0 else 'FREE'; raw=str(row.get('body_concerns','') or ''); concern=raw.split('|')[0] if raw else '편안한 핏'; uri=_data_uri(f"assets/products/{row.get('product_id')}.jpg")
 img=f"style=\"background-image:url('{uri}')\"" if uri else ''; inner='' if uri else '<span>PRODUCT IMAGE</span>'
 return f"<div class='product-card'><div class='product-image' {img}>{inner}</div><div class='product-copy'>{bh}<div class='product-brand'>{html.escape(str(row.get('brand','')))}</div><div class='product-name'>{html.escape(str(row.get('name','')))}</div><div class='product-price'>{int(row.get('price',0)):,}원</div><div class='product-meta'>♡ {sl} · {html.escape(concern)}</div></div></div>"
def brand_card_html(row):return f"<div class='brand-card'><div class='brand-card-name'>{html.escape(str(row.get('brand','')))}</div><div class='brand-card-desc'>{html.escape(str(row.get('description','')))}</div></div>"


def image_tag_html(rel,class_name='plain-image',alt=''):
 uri=_data_uri(rel)
 if not uri: return ''
 return f"<img class='{class_name}' src='{uri}' alt='{html.escape(alt)}'>"
