import html
def inject_css():
    import streamlit as st
    st.markdown("""<style>
    :root{--ff-red:#E54456;--ff-ink:#1b1b1b;--ff-gray:#777;--ff-line:#e8e8e8;--ff-soft:#f7f7f7;--ff-beige:#f7f3eb}
    .stApp{background:#fff;color:var(--ff-ink)}.block-container{max-width:1420px;padding-top:1.1rem;padding-bottom:4rem}[data-testid='stSidebar'],[data-testid='stSidebarCollapsedControl']{display:none!important}header[data-testid='stHeader']{background:transparent}
    .stButton>button{border-radius:999px;border:1px solid #e2e2e2;background:#fff;color:#252525;font-weight:600;min-height:42px}.stButton>button:hover{border-color:#cfcfcf;color:var(--ff-red)}.stButton>button[kind='primary']{background:var(--ff-ink);color:#fff;border-color:var(--ff-ink)}div[data-baseweb='input']>div{border-radius:999px!important;min-height:48px}
    .nav-icon{text-align:center;font-size:12px;font-weight:700;padding-top:12px;color:#333}.nav-rule{height:1px;background:#ededed;margin:.35rem 0 2rem}.eyebrow{font-size:12px;font-weight:800;letter-spacing:.08em;color:#555;margin-bottom:.7rem}.eyebrow.red{color:var(--ff-red)}
    .hero-title{font-size:clamp(40px,4vw,64px);line-height:1.08;letter-spacing:-.05em;margin:.2rem 0 1.6rem}.page-title{font-size:38px;line-height:1.15;letter-spacing:-.04em;margin:.1rem 0 1.3rem}.helper-label{font-size:12px;color:#888;margin:1.1rem 0 .45rem;font-weight:700}
    .live-card{margin-top:1.2rem;background:var(--ff-beige);border-radius:22px;padding:1.15rem 1.35rem 1.2rem}.live-top{font-size:12px;font-weight:800;color:#2d2d2d}.live-dot{display:inline-block;width:8px;height:8px;background:#2aa36b;border-radius:50%;margin-right:7px}.live-time{margin-left:12px;font-size:15px}.live-number{font-size:42px;font-weight:850;letter-spacing:-.04em;margin-top:.35rem}.live-label{font-size:13px;color:#666;margin-top:-.15rem}
    .discovery-banner{border-radius:26px;overflow:hidden;background:#f3f3f3;border:1px solid #ececec}.banner-image-placeholder{height:330px;background:linear-gradient(135deg,#e8e5e0 0%,#d6d9dc 100%);display:flex;align-items:center;justify-content:center}.image-note{font-size:12px;color:#8d8d8d;font-weight:800;letter-spacing:.12em}.banner-copy{padding:1.25rem 1.4rem 1.35rem;background:#fff}.banner-title{font-size:29px;line-height:1.18;letter-spacing:-.04em;font-weight:800;margin:.2rem 0 .55rem}.banner-sub{color:#777;font-size:13px}
    .section-gap{height:2.3rem}.section-gap-sm{height:1.4rem}.section-title-row{margin:1.5rem 0 .9rem}.section-title-main{font-size:24px;font-weight:800;letter-spacing:-.035em}.section-title-sub{color:#8b8b8b;font-size:12px;margin-top:.15rem}
    .product-card{border:1px solid #ececec;border-radius:18px;overflow:hidden;background:#fff;margin-bottom:.45rem}.product-image{height:225px;background:linear-gradient(135deg,#efebe6,#dde1e4);display:flex;align-items:center;justify-content:center}.product-image span{color:#9a9a9a;font-size:10px;font-weight:800;letter-spacing:.08em}.product-copy{padding:.85rem .9rem 1rem}.product-brand{font-size:10px;color:#8a8a8a;font-weight:700;margin-bottom:.22rem}.product-name{font-size:14px;font-weight:800;line-height:1.35;min-height:38px}.product-price{font-size:15px;font-weight:850;margin-top:.4rem}.product-meta{font-size:10px;color:#8a8a8a;margin-top:.35rem}.badge{display:inline-block;font-size:9px;font-weight:800;color:#fff;background:var(--ff-red);padding:3px 7px;border-radius:999px;margin-bottom:.4rem}
    .search-summary{background:#fafafa;border-radius:18px;padding:1rem 1.15rem;margin:1rem 0 1.4rem}.result-title{font-size:17px;font-weight:700}.chip-row{margin-top:.7rem;display:flex;flex-wrap:wrap;gap:7px}.filter-chip{background:#fff0f2;border:1px solid #f2b6bf;color:#c92d45;font-size:11px;font-weight:800;padding:6px 10px;border-radius:999px}.filter-title{font-size:16px;font-weight:800;margin-bottom:.9rem}.filter-count{background:#f7f3eb;padding:.8rem 1rem;border-radius:14px;margin-top:1rem;font-size:13px}.product-count{font-size:16px;font-weight:800;padding-top:.5rem}.empty-box{border:1px dashed #d9d9d9;border-radius:20px;padding:3rem;text-align:center}.empty-title{font-size:17px;font-weight:800}.muted{color:#888;font-size:12px;margin-top:.35rem}
    .brand-index{line-height:2.05;color:#555;border-top:1px solid #eee;border-bottom:1px solid #eee;padding:1rem 0;margin-bottom:1.5rem}.brand-card{border:1px solid #ececec;border-radius:18px;padding:1.2rem;min-height:125px;margin-bottom:.5rem}.brand-card-name{font-size:18px;font-weight:850}.brand-card-desc,.brand-desc{color:#777;font-size:12px;margin-top:.45rem;line-height:1.55}
    .product-image-tall{height:610px;border-radius:24px;background:linear-gradient(135deg,#efebe6,#d9dde1);display:flex;align-items:center;justify-content:center;color:#989898;font-size:12px;font-weight:800;letter-spacing:.1em}.detail-title{font-size:34px;line-height:1.2;letter-spacing:-.04em;margin:.35rem 0 .7rem}.detail-price{font-size:24px;font-weight:850;margin-bottom:1.25rem}.match-label{color:var(--ff-red);font-size:11px;font-weight:900;letter-spacing:.08em;margin-top:1.5rem}.why-box{background:#eef4ff;border-radius:18px;padding:1rem 1.1rem;margin:1.1rem 0 1rem}.why-title{color:#3565bc;font-size:12px;font-weight:900;margin-bottom:.35rem}.why-copy{font-size:13px;line-height:1.6;color:#3e4652}
    @media(max-width:900px){.block-container{padding-left:1rem;padding-right:1rem;padding-top:.5rem}.hero-title{font-size:42px}.page-title{font-size:30px}.banner-image-placeholder{height:270px}.product-image{height:185px}.product-image-tall{height:430px}.nav-icon{display:none}}
    </style>""",unsafe_allow_html=True)
def section_title(title,subtitle=''):
    import streamlit as st
    st.markdown(f"<div class='section-title-row'><div class='section-title-main'>{html.escape(str(title))}</div><div class='section-title-sub'>{html.escape(str(subtitle))}</div></div>",unsafe_allow_html=True)
def product_card_html(row):
    badge=str(row.get('badge','') or ''); bh=f"<div class='badge'>{html.escape(badge)}</div>" if badge else ''
    max_size=float(row.get('max_size',0)); size_label=f"{int(max_size)}까지" if max_size>0 else 'FREE'; concern=str(row.get('body_concerns','') or '').split('|')[0] or '데일리'
    return f"<div class='product-card'><div class='product-image'><span>PRODUCT IMAGE</span></div><div class='product-copy'>{bh}<div class='product-brand'>{html.escape(str(row.get('brand','')))}</div><div class='product-name'>{html.escape(str(row.get('name','')))}</div><div class='product-price'>{int(row.get('price',0)):,}원</div><div class='product-meta'>♡ {size_label} · {html.escape(concern)}</div></div></div>"
def brand_card_html(row): return f"<div class='brand-card'><div class='brand-card-name'>{html.escape(str(row.get('brand','')))}</div><div class='brand-card-desc'>{html.escape(str(row.get('description','')))}</div></div>"
def placeholder_image(label='IMAGE',tall=False): return f"<div class='{'product-image-tall' if tall else 'product-image'}'>{html.escape(label)}</div>"
