import base64, html, mimetypes
from pathlib import Path
ROOT=Path(__file__).resolve().parents[1]
def _data_uri(rel):
 p=ROOT/rel
 if not p.exists(): return None
 mime=mimetypes.guess_type(p.name)[0] or 'image/jpeg'
 return f"data:{mime};base64,"+base64.b64encode(p.read_bytes()).decode()
def inject_css():
 import streamlit as st
 st.markdown(r'''<style>
:root{--red:#E54456;--ink:#1B1B1B;--line:#E9E9E9;--beige:#F8F3E9;--blue:#EEF4FF}
*{font-family:Pretendard,"Noto Sans KR",Arial,sans-serif}.stApp{background:#fff;color:var(--ink)}.block-container{max-width:1420px;padding-top:1.1rem;padding-bottom:4rem}header[data-testid="stHeader"],[data-testid="stSidebar"],[data-testid="stSidebarCollapsedControl"]{display:none!important}
.stButton>button{border-radius:999px;border:1px solid #E4E4E4;background:#fff;color:#252525;font-weight:650;min-height:40px}.stButton>button:hover{border-color:#CACACA;color:var(--red)}.stButton>button[kind="primary"]{background:var(--ink);color:#fff;border-color:var(--ink)}
.st-key-topnav{padding-top:.3rem}.st-key-topnav .stButton>button{border:none!important;background:transparent!important;box-shadow:none!important;border-radius:0!important;min-height:34px!important;padding:.05rem .1rem!important;font-size:13px!important;font-weight:600!important}.st-key-topnav [data-testid="column"]:first-child .stButton>button{justify-content:flex-start!important;font-size:27px!important;font-weight:900!important;letter-spacing:-.045em!important;padding:0!important;line-height:1!important}.brand-subtitle{font-size:11px;color:#353535;margin-top:-.12rem;letter-spacing:-.025em}.nav-icon{text-align:center;font-size:15px;font-weight:700;padding-top:5px}.nav-icon.bag{font-size:11px;letter-spacing:.05em;padding-top:8px}.nav-rule{height:1px;background:#EBEBEB;margin:.8rem 0 2rem}
.st-key-discovery_panel{background:#fff;padding:0!important}.discovery-visual{height:365px;width:100%;background:linear-gradient(135deg,#E8E2D7,#D7DBDD);background-size:cover;background-position:center}.asset-fallback{height:100%;width:100%;display:flex;align-items:center;justify-content:center;color:#8D8D8D;font-size:11px;font-weight:850;letter-spacing:.13em}.discovery-copy{padding:1.05rem 1.35rem .45rem}.eyebrow{font-size:11px;font-weight:850;letter-spacing:.08em;color:#555;margin-bottom:.65rem}.eyebrow.red{color:var(--red)}.banner-title{font-size:30px;line-height:1.12;font-weight:900;letter-spacing:-.045em;margin:.15rem 0 .6rem}.banner-sub{color:#7A7A7A;font-size:12px}.st-key-discovery_panel .stButton>button[kind="primary"]{min-height:48px;font-size:13px}
.st-key-finder_console{border:1px solid #ECECEC;border-radius:28px;padding:1.55rem 1.7rem 1.3rem;background:#fff;box-shadow:0 10px 35px rgba(0,0,0,.018)}.hero-title{font-size:clamp(38px,3.6vw,56px);line-height:1.08;letter-spacing:-.055em;margin:.1rem 0 1.25rem}div[data-baseweb="input"]>div{min-height:48px!important;border-radius:5px!important;background:#F3F4F6!important;border-color:#F0F0F0!important}.helper-label{font-size:11px;color:#808080;margin:1.15rem 0 .45rem;font-weight:750}.st-key-finder_console .stButton>button:not([kind="primary"]){border:none!important;background:#F5F5F6!important;color:#3D3D3D!important;border-radius:5px!important;min-height:34px!important;padding:.25rem .55rem!important;font-size:11px!important;font-weight:600!important}
.live-board{margin-top:1rem;background:var(--beige);border-radius:18px;padding:1rem 1.15rem 1.05rem}.live-head{display:flex;justify-content:space-between;align-items:center;font-size:10px;font-weight:850}.live-dot{display:inline-block;width:8px;height:8px;border-radius:50%;background:#28A36A;margin-right:7px}.live-time{font-size:13px;font-weight:850}.live-body{display:grid;grid-template-columns:1.25fr 1.8fr .8fr;gap:12px;align-items:end;margin-top:.55rem}.live-kicker{font-size:13px;font-weight:750;letter-spacing:-.025em}.live-main{display:flex;align-items:baseline;justify-content:center;gap:6px}.live-prefix{font-size:12px;color:#6F6F6F;font-weight:700}.live-number{font-size:42px;line-height:1;font-weight:900;color:#8E1B28;letter-spacing:-.055em}.live-unit{font-size:13px;font-weight:850}.live-brand{font-size:13px;font-weight:850;text-align:right}
.quick-title{font-size:26px;line-height:1.1;font-weight:900;letter-spacing:-.045em;margin:1.55rem 0 .85rem .1rem}.circle-image{width:92px;height:92px;max-width:100%;aspect-ratio:1/1;margin:0 auto .25rem;border-radius:50%;background:linear-gradient(135deg,#E7E1D8,#D5DADD);background-size:cover;background-position:center;display:flex;align-items:center;justify-content:center;overflow:hidden}.circle-placeholder{font-size:9px;font-weight:850;color:#8D8D8D}.st-key-hero_row [data-testid="column"] .stButton>button{font-size:11px}
.section-gap{height:2.5rem}.section-title-row{margin:1.7rem 0 1rem}.section-title-main{font-size:25px;font-weight:900;letter-spacing:-.04em}.section-title-sub{color:#888;font-size:12px;margin-top:.15rem}.page-title{font-size:38px;line-height:1.15;letter-spacing:-.04em;margin:.1rem 0 1.3rem}
.product-card{border:1px solid #ECECEC;border-radius:18px;overflow:hidden;background:#fff;margin-bottom:.35rem}.product-image{height:245px;background:linear-gradient(135deg,#EFECE7,#DDE1E4);background-size:cover;background-position:center;display:flex;align-items:center;justify-content:center}.product-image span{color:#989898;font-size:10px;font-weight:850;letter-spacing:.09em}.product-copy{padding:.9rem 1rem 1rem}.product-brand{font-size:10px;color:#888;font-weight:750;margin-bottom:.2rem}.product-name{font-size:14px;line-height:1.35;font-weight:850;min-height:38px}.product-price{font-size:16px;font-weight:900;margin-top:.4rem}.product-meta{font-size:10px;color:#8A8A8A;margin-top:.35rem}.badge{display:inline-block;font-size:9px;font-weight:850;color:#fff;background:var(--red);padding:3px 7px;border-radius:999px;margin-bottom:.42rem}[class*="st-key-product_"] .stButton>button{border:none!important;background:transparent!important;border-radius:0!important;min-height:26px!important;padding:.05rem .1rem!important;font-size:11px!important;color:#555!important;justify-content:flex-start!important}
.search-summary{background:#FAFAFA;border-radius:18px;padding:1rem 1.15rem;margin:1rem 0 1.4rem}.result-title{font-size:17px;font-weight:750}.chip-row{margin-top:.7rem;display:flex;flex-wrap:wrap;gap:7px}.filter-chip{background:#FFF0F2;border:1px solid #F2B6BF;color:#C92D45;font-size:11px;font-weight:850;padding:6px 10px;border-radius:999px}.filter-title{font-size:16px;font-weight:850;margin-bottom:.9rem}.filter-count{background:var(--beige);padding:.8rem 1rem;border-radius:14px;margin-top:1rem;font-size:13px}.empty-box{border:1px dashed #D9D9D9;border-radius:20px;padding:3rem;text-align:center}.empty-title{font-size:17px;font-weight:850}.muted{color:#888;font-size:12px;margin-top:.35rem}.brand-index{line-height:2.1;color:#555;border-top:1px solid #EEE;border-bottom:1px solid #EEE;padding:1rem 0;margin-bottom:1.5rem}.brand-card{border:1px solid #ECECEC;border-radius:18px;padding:1.2rem;min-height:125px;margin-bottom:.5rem}.brand-card-name{font-size:18px;font-weight:850}.brand-card-desc,.brand-desc{color:#777;font-size:12px;margin-top:.45rem;line-height:1.55}.product-image-tall{height:610px;border-radius:24px;background:linear-gradient(135deg,#EFECE7,#D9DDE1);background-size:cover;background-position:center;display:flex;align-items:center;justify-content:center}.detail-title{font-size:34px;line-height:1.2;letter-spacing:-.04em;margin:.35rem 0 .7rem}.detail-price{font-size:24px;font-weight:900;margin-bottom:1.25rem}.match-label{color:var(--red);font-size:11px;font-weight:900;letter-spacing:.08em;margin-top:1.5rem}.why-box{background:var(--blue);border-radius:18px;padding:1rem 1.1rem;margin:1.1rem 0 1rem}.why-title{color:#3565BC;font-size:12px;font-weight:900;margin-bottom:.35rem}.why-copy{font-size:13px;line-height:1.6;color:#3E4652}
.floating-tools{position:fixed;right:22px;top:48%;display:flex;flex-direction:column;align-items:center;gap:10px;z-index:50}.floating-badge{width:48px;height:48px;border-radius:13px;background:#668C68;color:#fff;display:flex;align-items:center;justify-content:center;text-align:center;font-size:9px;font-weight:800;line-height:1.2;box-shadow:0 4px 14px rgba(0,0,0,.08)}.floating-icon{width:34px;height:34px;border-radius:50%;background:#fff;border:1px solid #EAEAEA;display:flex;align-items:center;justify-content:center;font-size:12px;font-weight:800;box-shadow:0 3px 12px rgba(0,0,0,.04)}.floating-icon.kakao{background:#FDE500;font-size:7px}
@media(max-width:900px){.block-container{padding-left:1rem;padding-right:1rem;padding-top:.65rem}.st-key-topnav [data-testid="column"]:not(:first-child){display:none}.st-key-hero_row [data-testid="stHorizontalBlock"]{display:flex!important;flex-direction:column-reverse!important;gap:1rem!important}.st-key-hero_row [data-testid="column"]{width:100%!important;flex:1 1 100%!important}.hero-title{font-size:40px}.st-key-finder_console{padding:1.15rem 1rem 1rem;border-radius:22px}.live-body{grid-template-columns:1fr;gap:6px}.live-main{justify-content:flex-start}.live-brand{text-align:left}.live-number{font-size:38px}.discovery-visual{height:320px}.banner-title{font-size:26px}.quick-title{font-size:23px}.circle-image{width:72px;height:72px}.floating-tools{display:none}.product-image{height:190px}.product-image-tall{height:430px}}
</style>''',unsafe_allow_html=True)
def asset_image_html(rel,fallback_label='IMAGE',class_name='discovery-visual'):
 uri=_data_uri(rel)
 return f"<div class='{class_name}' style=\"background-image:url('{uri}')\"></div>" if uri else f"<div class='{class_name}'><div class='asset-fallback'>{html.escape(fallback_label)}</div></div>"
def circle_image_html(rel,label=''):
 uri=_data_uri(rel)
 return f"<div class='circle-image' style=\"background-image:url('{uri}')\"></div>" if uri else f"<div class='circle-image'><span class='circle-placeholder'>{html.escape(label[:7])}</span></div>"
def section_title(title,subtitle=''):
 import streamlit as st
 st.markdown(f"<div class='section-title-row'><div class='section-title-main'>{html.escape(str(title))}</div><div class='section-title-sub'>{html.escape(str(subtitle))}</div></div>",unsafe_allow_html=True)
def product_card_html(row):
 badge=str(row.get('badge','') or ''); bh=f"<div class='badge'>{html.escape(badge)}</div>" if badge else ''
 maxs=float(row.get('max_size',0)); sl=f'{int(maxs)}까지' if maxs>0 else 'FREE'; raw=str(row.get('body_concerns','') or ''); concern=raw.split('|')[0] if raw else '편안한 핏'; uri=_data_uri(f"assets/products/{row.get('product_id')}.jpg")
 img=f"style=\"background-image:url('{uri}')\"" if uri else ''; inner='' if uri else '<span>PRODUCT IMAGE</span>'
 return f"<div class='product-card'><div class='product-image' {img}>{inner}</div><div class='product-copy'>{bh}<div class='product-brand'>{html.escape(str(row.get('brand','')))}</div><div class='product-name'>{html.escape(str(row.get('name','')))}</div><div class='product-price'>{int(row.get('price',0)):,}원</div><div class='product-meta'>♡ {sl} · {html.escape(concern)}</div></div></div>"
def brand_card_html(row):return f"<div class='brand-card'><div class='brand-card-name'>{html.escape(str(row.get('brand','')))}</div><div class='brand-card-desc'>{html.escape(str(row.get('description','')))}</div></div>"
